import Header from "./_layout/header/page"
import Footer from "./_layout/footer/page"
import './global.css'

export const metadata = {
  title: 'HARSH',
  description: 'Generated by Next.js in supervision of Harsh Panghal',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
  <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
