import Header from "./_layout/header/page"
import Footer from "./_layout/footer/page"
import './global.css'
import { ErrorWrapper } from "./error-wrapper"


export const metadata = {
  title: 'HARSH',
  description: 'Generated by Next.js in supervision of Harsh Panghal',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
  <Header/>
  <ErrorWrapper>  {children} </ErrorWrapper>
        <Footer/>
        </body>
    </html>
  )
}
