

export const metadata = {
  title: 'HARSH',
  description: 'Generated by Next.js in supervision of Harsh Panghal',
}

export default function RootLayout({ children }) {
  return (
          <>
    <h2>Featured products</h2>
        {children}
       
          </>
  )
}
